### PR TITLE
Fix bug that prevent users from getting write permission to use the E…

### PR DESCRIPTION
**Pull request by RodrigoDavy**
…xport feature

### CODE REVIEW

**Comment by TacoTheDank** [comment]
@RodrigoDavy 
Dude, you undid a lot of the code optimizations I made with your newest commit (https://github.com/RodrigoDavy/PixelArtist/commit/50e75cc94935373555c5cf363d4e61e6252a9a68). You either didn't update the testing branch with the master branch before making any changes, or something else, but whatever you did did a lot of damage. I suggest you undo https://github.com/RodrigoDavy/PixelArtist/commit/50e75cc94935373555c5cf363d4e61e6252a9a68 and force update the master branch and remote to erase the commit from history, as follows:

```git checkout master```
```git reset HEAD^1 --hard```
```git push origin -f```

(There was also no reason to update 3.0 to 3.0.1, seeing how you hadn't even tagged 3.0 yet :/ )

Now just make these changes in MainActivity.java:
the [new import](https://github.com/RodrigoDavy/PixelArtist/commit/50e75cc94935373555c5cf363d4e61e6252a9a68#diff-274bb379a2a233654914518fc944e55eR46), the [final int](https://github.com/RodrigoDavy/PixelArtist/pull/26/commits/4c901502661540d9bd5a97315c6ec48d0a1f6106#diff-274bb379a2a233654914518fc944e55eR63), the [selfPermissionCheck](https://github.com/RodrigoDavy/PixelArtist/pull/26/commits/4c901502661540d9bd5a97315c6ec48d0a1f6106#diff-274bb379a2a233654914518fc944e55eR437) (removing the "checkWriteExternalPermission"), and the [onRequestPermissionsResult](https://github.com/RodrigoDavy/PixelArtist/pull/26/commits/4c901502661540d9bd5a97315c6ec48d0a1f6106#diff-274bb379a2a233654914518fc944e55eR494) (removing [this](https://github.com/RodrigoDavy/PixelArtist/pull/26/commits/4c901502661540d9bd5a97315c6ec48d0a1f6106#diff-274bb379a2a233654914518fc944e55eL499))

Thank you.

**Comment by RodrigoDavy** [comment]
Sorry, as you can tell, I don't have that much experience with git. I did the changes you suggested, could you confirm that everything is ok now? Thanks :)

**Comment by TacoTheDank** [comment]
Sorry if that came across as a little harsh lol. Don't worry, git used to frustrate me a lot as well.

Yes, the changes are perfect. Thank you :)

**Comment by RodrigoDavy** [comment]
No problem, thanks for helping and contributing :D

**Comment by TacoTheDank** [comment]
@RodrigoDavy Just remember to tag 3.0 as well now ;)

**Comment by TacoTheDank** [comment]
Also, do you know why the app is no longer on the play store? :/

**Comment by RodrigoDavy** [comment]
By tagging, you mean making a GitHub release? (I'm about to do that) Or doing some modification in the source code?

I never uploaded my app to the Play Store, it's available through F-Droid though

**Comment by TacoTheDank** [comment]
Tagging a GitHub release for F-Droid, yeah.

That's strange, because it's [available on APKPure](https://apkpure.com/pixel-art/rodrigodavy.com.github.pixelartist), which I think isn't possible without the app having been on the Play Store. But then again, there's also VidMate and other such apps available as well, but those are super popular. This app is entirely unknown. So how would it get there? Hmm...

**Comment by RodrigoDavy** [comment]
Oh, boy! From the screenshots this is totally my app. I love seeing the screenshots they made with it hahahahahah

I'm guessing someone else saw my app and decided to upload it to the Play Store and somehow it got removed. I never intended to upload it to the Play Store because there are ton of apps with the same purpose that probably do a better job than my own. But, who knows?

It's kind of weird to think that someone just uploaded it to the Play Store though

**Comment by TacoTheDank** [comment]
Hmm lol

**Comment by TacoTheDank** [comment]
@RodrigoDavy did you get this?

also I'm currently adding a shitton more colors and a custom-made adaptive icon (arguably better than the current square one), so stay tuned :P

**Comment by RodrigoDavy** [comment]
I deleted one of the tags

Awesome, I'm looking forward to see what you're working on! :)

**Pull request closed without merging**
